### ISSUE TITLE
IIFE :eggplant: 

### ISSUE THREAD

**Issue by hdrdavies** [kat4/KatOver4low#23]
(Immediately invoked function expression) here: 

https://github.com/kat4/KatOver4low/blob/master/controllers/handler.js#L10

Appaz it's not necessary, see here:

https://github.com/liberty-x/lxriddle/issues/26

You can module.exports an object with key-value pairs which are functions:

https://github.com/liberty-x/lxriddle/blob/master/handler.js#L87

**Comment by mantagen** [comment]
Good thinking thanks bro.

Will do this next time or similar :0

**Comment by mantagen** [comment]
Please close this issue

**Comment by hdrdavies** [comment]
alright - but you haven't resolved it
