### ISSUE TITLE
Pushing to master?

### ISSUE THREAD

**Issue by claireinez** [kat4/KatOver4low#29]
Are you seriously still doing this?? (I am on my phone so a bit difficult to tell...but the commit history seems highly suspicious)

**Comment by katpas** [comment]
Only this morning while we were debugging heroku as a group. Otherwise it's been pull requests all day every day.

**Comment by msmichellegar** [comment]
Hmmm...

**Comment by katpas** [comment]
Thanks for keeping an eye on us.
